# Generated by Django 4.2.4 on 2023-09-02 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDRLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('call_duration', models.IntegerField()),
                ('MSISDN', models.CharField(max_length=20)),
                ('call_date', models.DateField()),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_information.customer')),
            ],
        ),
    ]
