# Generated by Django 4.2.4 on 2023-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0007_cdrlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50, null=True)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('sector', models.CharField(max_length=50, null=True)),
                ('cells', models.CharField(max_length=50, null=True)),
                ('village', models.CharField(max_length=50, null=True)),
                ('sitename', models.CharField(max_length=50, null=True)),
                ('sitetechnology', models.CharField(max_length=50, null=True)),
                ('cellid', models.IntegerField(null=True)),
            ],
        ),
    ]
