# Generated by Django 4.2.4 on 2023-09-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_limit', models.IntegerField()),
                ('talk_time_limit', models.IntegerField()),
                ('sms_limit', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
