# Generated by Django 4.2.4 on 2023-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0009_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdrlog',
            old_name='customer_name',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='cdrlog',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='cdrlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
