# Generated by Django 4.2.4 on 2023-09-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0010_rename_customer_name_cdrlog_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrlog',
            name='status',
            field=models.IntegerField(default='active'),
        ),
    ]
