# Generated by Django 4.2.4 on 2023-09-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0011_alter_cdrlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrlog',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
